services:

  - type: web

    plan: free

    name: FileShare

    env: python

    buildCommand: pip install -r requirements.txt

    startCommand: python bot.py

    repo: https://github.com/Maheshbot99/FileShare.git      

    branch: main

    envVars:

      - key: TG_BOT_TOKEN 

        sync: false

      - key: API_ID 

        sync: false

      - key: API_HASH 

        sync: false

      - key: FORCE_SUB_CHANNEL 

        sync: false

      - key: DATABASE_NAME 

        sync: false

      - key: DATABASE_URL 

        sync: false 

      - key: START_MESSAGE 

        sync: false

      - key: ADMINS

        sync: false    

      - key: FORCE_SUB_MESSAGE

        sync: false    

      - key: OWNER_ID

        sync: false    

      - key: OWNER_ID

        sync: false    
    autoDeploy: false 
