services:

  - type: web

    plan: free

    name: FileShare

    env: python

    buildCommand: pip install -r requirements.txt

    startCommand: python bot.py

    repo: https://github.com/Maheshbot99/FileShare.git      

    branch: main

    envVars:

      - key: TG_BOT_TOKEN 

        sync: false

      - key: API_ID 

        sync: false

      - key: API_HASH 

        sync: false

      - key: FORCE_SUB 

        sync: false

      - key: DATABASE_NAME 

        sync: false

      - key: DATABASE_URL 

        sync: false 

      - key: START_PIC 

        sync: false

      - key: ADMIN 

        sync: false    

    autoDeploy: false 
